# Generated by Django 4.2.6 on 2024-03-17 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('cc_usu', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direcion', models.CharField(max_length=80)),
                ('contacto_ememergenci', models.CharField(max_length=20)),
                ('nombre_contacto', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=70)),
                ('eps', models.CharField(max_length=20)),
                ('contrasenaU', models.CharField(max_length=400)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('caja_de_compensacion', models.CharField(max_length=50)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='adicionales',
            fields=[
                ('id_adi', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('valor', models.FloatField()),
                ('empleado_A_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('numero_doc', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de Documento')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('numero_contacto', models.CharField(max_length=25, verbose_name='Número de Contacto')),
                ('contrasenaaC', models.CharField(max_length=400, verbose_name='Contraseña')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
        ),
        migrations.CreateModel(
            name='estado_cliente',
            fields=[
                ('estado', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='estado_empleados',
            fields=[
                ('esatado_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='estado_habitacion',
            fields=[
                ('estado_reserva', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='estado_reserva',
            fields=[
                ('estado_reserva', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('numero_H', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cantidad_p', models.CharField(max_length=20)),
                ('valor_habitacion', models.FloatField()),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.estado_habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='mobiliario',
            fields=[
                ('id_mobi', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('camas_sencillas', models.CharField(max_length=20)),
                ('camas_doble', models.CharField(max_length=20)),
                ('camas_king', models.CharField(max_length=20)),
                ('tv_plano', models.CharField(max_length=20)),
                ('sala', models.CharField(max_length=20)),
                ('sillas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('tipo_servicio', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_documento',
            fields=[
                ('tipo_documento', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_empleado',
            fields=[
                ('tipo_empleado', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_habitacion',
            fields=[
                ('tipo_habitacion', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecah_ini', models.DateTimeField()),
                ('fecah_fin', models.DateTimeField()),
                ('valor_reserva', models.FloatField()),
                ('estado_res', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.estado_reserva')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.habitacion')),
                ('numero_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='huspedes_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.reserva')),
                ('numero_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_mobi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.mobiliario'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.tipo_habitacion'),
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('pago_total', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('empleado_A_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detalles_factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('valor_reserva', models.FloatField()),
                ('valor_adicional', models.FloatField()),
                ('id_adi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.adicionales')),
                ('id_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.ForeignKey(blank=True, default='Activo', null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.estado_cliente', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.tipo_documento', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='adicionales',
            name='id_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.reserva'),
        ),
        migrations.AddField(
            model_name='adicionales',
            name='id_servi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.servicios'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='codigo_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.tipo_empleado'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apia.estado_empleados'),
        ),
    ]
